# AutoTreeChop by Maoyue
# Discord support server: https://discord.gg/uQ4UXANnP2
# Spigot Page: https://www.spigotmc.org/resources/113071
# Source code: https://github.com/milkteamc/AutoTreeChop

# The plugin locale (<language>-<country>-<variant>)
# en, de, zh, zh-TW, en-US, de-DE, de-AU, ...
# See all available language in lang folder.
# Open a PR at our GitHub to let plugin support more language!
locale: en

# If set to true, the plugin will automatically translate to the locale of the player (if there are translations present)
use-player-locale: false

# The number of times non-VIP players can chop down trees per day,
# you can give everyone "autotreechop.vip" permission to disable it.
max-uses-per-day: 50

# MySQL setting
# If "useMysql: false", plugin will use SQLite
useMysql: false
hostname: example.com
port: 3306
database: example
username: root
password: abc1234

# If disable, VIP have unlimited usage
limitVipUsage: true
# Will only work when you enable limitVipUsage
vip-uses-per-day: 100
vip-blocks-per-day: 1000

# Tree blocks that non-VIP players can chop down every day,
# you can give everyone "autotreechop.vip" permission to disable it.
max-blocks-per-day: 500

# Use visual effect
visual-effect: true

# damage tool when chopping tree
toolDamage: true

# Enable this for better performance, but this may cause issue sometime.
chopTreeAsync: true

# Stop chopping if the blocks are not connected (not part of the same tree)
stopChoppingIfNotConnected: false

# Stop chopping if the blocks are of different types
stopChoppingIfDifferentTypes: false

# How much durability should be decrease when player brock one block.
toolDamageDecrease: 1

# Define which materials are log
# Fun fact: If you add "DIAMOND_ORE", this plugin can become an auto mining plugin, lol
log-types:
  - OAK_LOG
  - BIRCH_LOG
  - SPRUCE_LOG
  - JUNGLE_LOG
  - ACACIA_LOG
  - DARK_OAK_LOG
  - MANGROVE_LOG
  - CHERRY_LOG

